pipeline {
    agent { docker 
    {
		image 'maven:3.3.3'
		customWorkspace 'c:\\devtools\\foq'          
      }
 }
    stages {
        stage('build') {
            steps {
                echo 'Building..'
            }
        }
        
    }
} 