pipeline {
    agent 'any'
    options { 
    			buildDiscarder(logRotator(numToKeepStr: '10')) 
    		}
    parameters
   			{
    			string(name: 'mailingList', defaultValue: 'psavi@softserveinc.com', description: 'Mailing list')    
			}
    stages {
        stage('build') {
            steps {
                bat 'mvn -f csms-frk/pom.xml -Dcom.cosmos.grid.hub.url=http://localhost:4444/grid -Dcom.cosmos.driver.browser=chrome -Dcom.cosmos.execution.type=local -Dcom.cosmos.configuration.strategy=env -Dcom.cosmos.driver.executable.location=C:\\devtools\\drivers\\chrome\\2.34\\chromedriver_win32\\chromedriver.exe -Dcom.cosmos.steps.context.scope=feature -Dcom.cosmos.logs.location=logs clean test'
            }
        }        
    }
    post {
        always {
            allure 	results: [[path: 'csms-frk/allure-results']]
            archive "csms-frk/logs/**/*"
            archive "csms-frk/logs/*"
            deleteDir()
            echo "Sending notifications to: ${params.mailingList} ..."
            mail    subject : "${JOB_NAME} - Build # ${BUILD_NUMBER} - ${currentBuild.result}!",
                	body : "Please see ${BUILD_URL}",
                	from : 'medispend_ci@projects.softservecom.com',
                	to : "${params.mailingList}"

        }        
    }
}